[[channels]]
id = 0
name = "Main Mix"

[[channels]]
id = 1
name = "Mellow Mix"

[[channels]]
id = 2
name = "Rock Mix"

[[channels]]
id = 3
name = "World/Etc"

[tracking]
url = "https://api.radioparadise.com/api/now_playing?chan=%s"
contact = "your-email@example.com"
database = "./rp_tracks.db"

[recording]
output = "./recordings"
cuesheet = true
tracklist = true

[[streams]]
channel = 0
url = "https://stream.radioparadise.com/aac-320"
type = "mp4"

# [[jobs]]
# name = "RP Mellow Mix"
# url = "https://stream.radioparadise.com/mellow-320"
# type = "mp4"
# cuesheet = false

# [[jobs]]
# name = "RP Rock Mix"
# url = "https://stream.radioparadise.com/rock-320"
# type = "mp4"
# cuesheet = false
# tracklist = false

# [[jobs]]
# name = "RP World/Etc Mix"
# url = "https://stream.radioparadise.com/world-etc-320"
# type = "mp4"
